### ISSUE TITLE
not working anymore?

### ISSUE THREAD

**Issue by julien9999** [Kira2/parse-server-sendinblue-adapter#1]
Hi,
Is it still working?
I can't make it work, please help.
Maybe we could upgrade to sendinblue latest sdk?

Thanks in advance

**Comment by Kira2** [comment]
Hi,

I currently use it into one of my production server, and the emails are correctly sent. It's difficult to say what's going on without a more specific description. Maybe have you an error message or some logs on your side to know exactly what the problem is? Otherwise, it will be difficult to help.

Best regards,

**Comment by julien9999** [comment]
Error: Cannot find module './model/RequestSmsRecipientExport'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
at Function.Module._load (internal/modules/cjs/loader.js:507:25)
at Module.require (internal/modules/cjs/loader.js:637:17)
at require (internal/modules/cjs/helpers.js:20:18)
at /app/node_modules/sib-api-v3-sdk/src/index.js:23:4527
at Object.<anonymous> (/app/node_modules/sib-api-v3-sdk/src/index.js:25:2)
at Module._compile (internal/modules/cjs/loader.js:689:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
at Module.load (internal/modules/cjs/loader.js:599:32)
at tryModuleLoad (internal/modules/cjs/loader.js:538:12)

**Comment by julien9999** [comment]
https://github.com/sendinblue/APIv3-nodejs-library/issues/32

**Comment by Kira2** [comment]
This is the related issue [https://github.com/sendinblue/APIv3-nodejs-library/issues/32](https://github.com/sendinblue/APIv3-nodejs-library/issues/32)

As you said, an upgrade to the latest SendinBlue SDK version should fix this. You can test it and launch the integration tests to be sure that everything's work fine before submitting a pull-request. Or I will do it when I will have time.

Otherwise, explicitly set this line ``"sib-api-v3-sdk": "3.1.2"``  into the dependencies of your package.json file to deploy your server should fix this with APIv3 version

```
{
    "dependencies": {
        ....
        "sib-api-v3-sdk": "3.1.2"
    }
}
```

**Comment by julien9999** [comment]
Adding "sib-api-v3-sdk": "3.1.2" directly to the package.json fixed the initial issue.
I now have the following error when sending a requestPasswordReset:


(node:20) UnhandledPromiseRejectionWarning: Error: Forbidden
at Request.callback (/app/node_modules/superagent/lib/node/index.js:675:11)
at /app/node_modules/superagent/lib/node/index.js:883:18
at IncomingMessage.<anonymous> (/app/node_modules/superagent/lib/node/parsers/json.js:16:7)
at IncomingMessage.emit (events.js:187:15)
at IncomingMessage.EventEmitter.emit (domain.js:442:20)
at endReadableNT (_stream_readable.js:1085:12)
at process._tickCallback (internal/process/next_tick.js:63:19)

(node:20) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

**Comment by Kira2** [comment]
Hi

The two important things I see into your logs are these:

```
UnhandledPromiseRejectionWarning: Error: Forbidden
```

```
(node:20) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

The first one indicates that you try to process an operation that is **forbidden**. Maybe because you didn't configure the package correctly by specifying the correct SendinBlue API key or whatever.

The second specifies that a promise failed without any catch block. Probably because the operation was forbidden.

Check that you have configured the package correctly to use it with your SendinBlue account, and use a catch block into each promise to handle the errors.

**Comment by juliengatt** [comment]
Hi, it looks like the error came from the fact that my account wasn’t fully approved. 
Thanks for your help and responsiveness.

**Comment by julien9999** [comment]
Hi, it looks like the error came from the fact that my account wasn’t fully approved.
Thanks for your help and responsiveness.

**Comment by Kira2** [comment]
Thanks for your feedback. Glad to hear that it worked after the approval of your Sendinblue account.
